runtime: php74

handlers:
# Serve a directory as a static resource.
- url: /.*
  script: index.php
       
- url: /app/.*
  script: auto
- url: /app/Controllers.* 
  script: auto
- url: /app/Views.*
  script: auto