- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  secretEnv: [ 'APP_SETUP_URL', 'APP_SETUP_TOKEN' ]
  args:
  -   "-c"
  - |
    RESPONSE=$(curl -o /dev/null -s -w   "%{http_code}" \
        -d "APP_SETUP_TOKEN=$$APP_SETUP_TOKEN" \
        $_APP_BASE_URL/$$APP_SETUP_URL)

    if [ "200" != "$$RESPONSE" ];
    then
      echo "FAIL: migrations failed"
      exit 1;
    else
      echo "PASS: migrations ran successfully"
    fi
